demeter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('demeter_app.urls')),
]

demeter_app/urls.py
"""Define url patterns."""

from django.urls import path

from . import views

app_name = 'demeter_app'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page for adding meals
    path('add_meal/', views.add_meal, name='add_meal'),
    path('your_meals/', views.your_meals, name='your_meals'),
    path('stats/', views.stats, name='stats'),
    path('view_meal/<int:meal_id>/', views.view_meal, name='view_meal'),
]

users/urls.py
"""URL patterns for the users."""

from django.urls import path, include, reverse_lazy

from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'
urlpatterns = [
    # Default authorisation urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
    # Password reset urls.
]

demeter_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Nation(models.Model):
    """Contains a list of the countries."""
    country = models.CharField(max_length=50, primary_key=True)
    continent = models.CharField(max_length=20)
    national_dish = models.CharField(max_length=50)

    def __str__(self):
        return self.country

class Meal(models.Model):
    """Contains a list of meals and their details."""
    member = models.ForeignKey(User, on_delete=models.CASCADE)
    meal = models.CharField(max_length=50)
    country = models.ForeignKey(Nation, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'User: {self.member} - Meal: {self.meal} - Country: {self.country} - \
Date Added: {self.date_added}'

demeter_app/forms.py
from django import forms

from .models import Meal, Nation

class MealForm(forms.ModelForm):
    class Meta:
        model = Meal
        fields = ['meal', 'country']

demeter_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import CreateView
from django.db.models import Count
from django.http import Http404

from .forms import MealForm
from .models import Nation, Meal
from django.contrib.auth.decorators import login_required

import random

def index(request):
    """The home page."""
    continent_counts, total_countries = display_country_totals()
    context = {
        'countries_per': continent_counts, # amount of countries per continent
        'total_countries': total_countries, # total amount of countries in world
    }
    return render(request, 'demeter_app/index.html', context)

@login_required
def add_meal(request):
    """Add a meal."""
    if request.method != 'POST':
        form = MealForm()
    else:
        form = MealForm(data=request.POST)
        if form.is_valid:
            new_meal = form.save(commit=False)
            new_meal.member = request.user
            new_meal.save()
            return redirect('demeter_app:your_meals')

    context = {'form': form}
    return render(request, 'demeter_app/add_meal.html', context)

@login_required
def your_meals(request):
    """Displays all meals associated with a user."""
    meals = Meal.objects.filter(member=request.user).order_by('country')
    if not meals:
        meals = False
    country_continents = completion_counter(request)
    context = {
        'meals': meals, # meals member has made
        'countries': country_continents, # unique countries completed and their continents
        }
    return render(request, 'demeter_app/your_meals.html', context)

@login_required
def stats(request):
    """Displays the stats regarding the completion of countries by continent."""
    country_continents, country_counter = completion_counter(request)
    country_totals, overall_total = display_country_totals()
    completion_percentages, overall_percent = completion_percent(
        country_counter,
        country_totals
        )
    next_meal = random_choice(
        request,
        completion_percentages,
        country_continents
        )
    context = {
        'countries': country_continents, # unique countries completed and their continents
        'count': country_counter, # amount of countries completed
        'totals': country_totals, # total countries in each continent
        'percentages': completion_percentages, # percent of continent completed
        'overall_percent': overall_percent, # percent of world completed
        'next_meal': next_meal # next meal suggestion
        }
    return render(request, 'demeter_app/stats.html', context)

def random_choice(request, completion_percentages, country_continents):
    """
    Suggests an new country to complete based on which continent
    you have done less of.
    """
    next_continent = min(
        completion_percentages,
        key=completion_percentages.get
        )

    # Gets a query set of all countries in next continent
    next_continent_options = Nation.objects.filter(
        continent=next_continent
        ).values_list('country', flat=True)
    meals_list = Meal.objects.filter(
        member=request.user
        ).values_list('country', flat=True)
    # Need to exclude any country already done from the selection
    next_continent_options = next_continent_options.exclude(country__in=meals_list)

    # choose a random country from the next continent
    next_country = random.choice(next_continent_options)
    # search the Nations table so we have access to the national dish
    next_meal = Nation.objects.get(country=next_country)
    
    return next_meal

def completion_counter(request):
    """Returns the countries where meals have been made."""
        # Get the amount of different countries meals have been made for
    unique_countries = Meal.objects.order_by().values_list(
        'country',
        flat=True
        ).distinct()
    unique_countries = unique_countries.filter(member=request.user)
    # Create k-v pairs of county and continent
    country_continents = Nation.objects.filter(
        country__in=unique_countries
        ).values('country', 'continent')
    country_counter = {}
    # For loop to count countries completed
    for country_continent in country_continents:
        key_entry = country_continent['continent']
        if key_entry not in country_counter:
            country_counter[key_entry] = 1
        else:
           country_counter[key_entry] += 1
    return country_continents, country_counter

def completion_percent(country_counter, country_totals):
    """Calculates percentage of continents completed, plus overall."""
    completion_percentages = {}
    overall_total = 0 # overall total of countries completed
    total_countries = 0 # Incase the amount of countries change!
    for k, v in country_totals.items():
        if k not in country_counter:
            country_counter[k] = 0
        completion_percentages[k] = str(round(
            (country_counter[k] / country_totals[k] * 100), 2
            )) + "%"
        overall_total += country_counter[k]
        total_countries += country_totals[k]
    # Add an overall percentage to the dictionary
    overall_percent = str(round(
           (overall_total / total_countries * 100), 2
           )) + "%"
    return completion_percentages, overall_percent

@login_required
def view_meal(request, meal_id):
    """Displays a single meal."""
    meal = get_object_or_404(Meal, id=meal_id)
    # Redirect the member if they try to go to someone else's meal
    if meal.member != request.user:
        return redirect('demeter_app:your_meals')
    context = {'meal': meal}
    return render(request, 'demeter_app/view_meal.html', context)

def display_country_totals():
    """Display the totals of countries both by continent and world."""
    continents = Nation.objects.values('continent').annotate(
        Count('continent')
    )
    # Create a k-v pair for continent and counts
    continent_counts = {d['continent']: d['continent__count'] for d in continents}
    total_countries = 0
    for k, v in continent_counts.items():
        total_countries += v
    return continent_counts, total_countries

demeter_app/templates/demeter_app/add_meal.html
{% extends "demeter_app/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h1 class="title">Add a new meal</h1>
{% endblock page_header %}

{% block content %}

<h4>What is your meal?</h4>
<form action="{% url 'demeter_app:add_meal' %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-secondary">Add meal</button>
    {% endbuttons %}
</form>

{% endblock content %}

demeter_app/templates/demeter_app/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Demeter</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery="full" %}
    <style>
      .title {
        font-family: "Lucida Console",
        "Courier New", monospace;
      }
    </style>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-8 border">
  <div class="container-fluid">
    <a class="navbar-brand" style=margin-top:-4px href="{% url 'demeter_app:index' %}">Demeter</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        {% if user.is_authenticated %}
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <span class ="navbar-text">What will you cook today, {{ user.username }}?</span></li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link"
                href="{% url 'demeter_app:add_meal' %}">Add a Meal!</a></li>
            <li class="nav-item">
              <a class="nav-link"
                href="{% url 'demeter_app:your_meals' %}">Your Meals!</a></li>
            <li class="nav-item">
              <a class="nav-link" 
                href="{% url 'users:password_change' %}">Change password?</a></li>
            <li class="nav-item">
              <a class="nav-link" 
                href="{% url 'users:logout' %}">Log out!</a></li>
        {% else %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" 
                href="{% url 'users:login' %}">Log in!</a></li>
            <li class="nav-item">
              <a class="nav-link" 
                <a href="{% url 'users:register' %}">Register!</a></li>
          </ul>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<main role="main" class="container-fluid">
  <div class="pb-2 mb-2 border-bottom">
  </br>
    {% block page_header %}{% endblock page_header %}
  </div>
  <div>
    {% block content %}{% endblock content %}
  </div>
</main>

</body>
</html>

demeter_app/templates/demeter_app/index.html
{% extends 'demeter_app/base.html' %}

{% block page_header %}
<h1 class="title">Up for the Demeter challenge?</h1>
{% endblock page_header %}

{% block content %}

<p>Keep track of your journey to cook a meal from every country in the world!</br>
There are {{ total_countries }} countries (albeit debateable)! Breakdown as follows:</br>
</p>

<ul>
    {% for k, v in countries_per.items %}
        <li>{{ k }} has {{ v }} countries!</li>
    {% endfor %}
</ul>

<p>Can you cook a meal for each country?</p>

{% endblock content %}

demeter_app/templates/demeter_app/stats.html
{% extends 'demeter_app/base.html' %}

{% block page_header %}
<h1 class="title">Your Statistics</h1>
{% endblock page_header %}

{% block content %}

<p>Countries completed by continent:</p>

{% regroup countries|dictsort:"continent" by continent as continent_list %}

<ul>
    {% for continent in continent_list %}
        <li>{{ continent.grouper }} - {{ percentages|get_item:continent.grouper }} completed!</li>
            <ul>
            {% for country in continent.list %}
                <li>{{ country.country }}</li>
            {% endfor %}
            </ul>
        </li>
    {% endfor %}
</ul>

{% if overall_percent == "100.0%" %}
    <p>You have made a meal from every country and completed the challenge! Congrats!</p>
{% else %}
    <p>You have completed {{ overall_percent }} of the total countries in the world!</p>

    <p>Why don't you try <b>{{ next_meal.national_dish }}</b> from <b>{{ next_meal.country }}</b> next? Try it now. Now.</p>
{% endif %}

{% endblock content %}

demeter_app/templates/demeter_app/view_meal.html
{% extends 'demeter_app/base.html' %}

{% block page_header %}
<h1 class="title">{{ meal.meal }}</h1>
{% endblock page_header %}

{% block content %}

<p>A meal from {{meal.country}}, {{meal.country.continent}}.</br>
You made this on {{meal.date_added}}</p>

{% endblock content %}

demeter_app/templates/demeter_app/your_meals.html
{% extends 'demeter_app/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
<h1 class="title">Your Meals</h1>
{% endblock page_header %}

{% block content %}

{% if meals == False %}
    <p>Awww, you haven't made any meals...</p>
    <a href="{% url 'demeter_app:add_meal' %}">Add a Meal!</a>
{% else %}
    <p>Here is your current list of your meals!</p>

    <ul>
        {% for meal in meals %}
            <li>
                <a href="{% url 'demeter_app:view_meal' meal.id %}">{{ meal.meal }}</a>
                from {{ meal.country }}, {{ meal.country.continent }}
            </li>  
        {% endfor %}
    </ul>
    {% buttons %}
    <button class="btn btn-secondary" onclick="location.href={% url 'demeter_app:add_meal' %}">Add a Meal!</button>
    <button class="btn btn-secondary" onclick="location.href={% url 'demeter_app:stats' %}">Meal Statistics!</button>
    {% endbuttons %}
{% endif %}

{% endblock content %}